---
# Connection settings for docker host
ansible_host: "{{ docker_pve2_ip }}"
ansible_user: dockeruser

# USB backup drive configuration for Zerobyte
backup_drive_uuid: "dd5c8bf2-a1a1-406d-a8c9-62acb67f1704"
