---
# Connection settings for docker host
ansible_host: "{{ docker_pve2_ip }}"
ansible_user: dockeruser

# USB backup drive configuration for Zerobyte
backup_drive_uuid: "00c24c12-e1c1-46ef-ae52-01ac0548f75b"
