---
all:
  children:
    rpi:
      hosts:
        rpi:
          ansible_connection: local
    proxmox:
      hosts:
        samba-share:
          ansible_host: "{{ samba_share_ip }}"
          ansible_user: root
...